4mission/Models/grademodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _4mission.Models
{
    public class grademodel
    {
        [Required]
        [Range(0, 100)]
        public int Assignment { get; set; }
        [Required]
        [Range(0, 100)]
        public int Group { get; set; }
        [Required]
        [Range(0, 100)]
        public int Quiz { get; set; }
        [Required]
        [Range(0, 100)]
        public int Midterm { get; set; }
        [Required]
        [Range(0, 100)]
        public int Final { get; set; }
        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }
    }
}

4mission/Controllers/BlahController.cs
using _4mission.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _4mission.Controllers
{
    public class BlahController : Controller
    {
      
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Grade ()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Grade(grademodel model)
        {
            return View();
        }
    }
}

4mission/Views/Blah/Grade.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model grademodel;
 
<nav>
    <a asp-controller="Blah" asp-action="Index">Home</a>
    <a asp-controller="Blah" asp-action="Grade">Grade</a>
</nav>

<h2>Grade Calculator:</h2>
<!-- grade calculator that takes inputs, then the javascript is going to add them together and spit out the total percentage.-->
<form method="post">
    <label for="assignments">Assignments (between 1 and 50):</label>
    <input type="number" id="input1" asp-for="Assignment" min="1" max="50"><br />
    <label for="groupproject">Group Project (between 1 and 10):</label>
    <input type="number" id="input2" asp-for="Group"min="1" max="10"><br />
    <label for="quizzes">Quizzes (between 1 and 10):</label>
    <input type="number" id="input3"asp-for="Quiz" min="1" max="10"><br />
    <label for="midterm">Midterm Exam (between 1 and 10):</label>
    <input type="number" id="input4" asp-for="Midterm" min="1" max="10"><br />
    <label for="final">Final Exam (between 1 and 10):</label>
    <input type="number" id="input5" asp-for="Final" min="1" max="10"><br />
    <label for="intex">INTEX (between 1 and 10):</label>
    <input type="number" id="input6" asp-for="Intex" min="1" max="10"><br />
    <button type="submit" id="submit">Submit</button>
    <span id="answers"></span>
</form>
<!--gotta link up the bootstrap, jquery and js links so the other parts of the website work.-->

<script src="js/grade.js"></script>

4mission/Views/Blah/index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Jessica Holt";

}

<nav>
    <a asp-controller="Blah" asp-action="Index">Home</a>
    <a asp-controller="Blah" asp-action="Grade">Grade</a>
</nav>

<!--header with my preferred name-->
<h1>Jessica Holt</h1>
<img src="img/IMG_3328.jpg" />
<!-- paragraph about what I hope to get out of this course-->
<p>I would love to be comfortable with the whole process of ASP.Net so that I don't feel like I'm drowning when I get an internship or full time job in the future!:)</p>
<br />
<!--list of top jobs I want upon graduation ;) -->
<p>Top #3 jobs I am most interested in pursuing when I graduate:</p>
<ul>
    <li>Database Administrator/ Soccer Mom</li>
    <li>Model</li>
    <li>NFL Football Head Coach</li>
</ul>

4mission/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
     <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <!--Gotta add bootstrap at the top so it applies-->
    <link href="lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" />
    <!-- add icon link -->
    <link rel="icon" href="https://cdn.icon-icons.com/icons2/3786/PNG/96/flower_plant_nature_rose_icon_232532.png"
          type="image/x-icon">


</head>
<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="Grade">Grade</a>
    </nav>


    <div>
        @RenderBody()
    </div>

    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>

</body>
</html>